name: Docker Image CI

on:
  push:
    branches: [ "docker" ]
  pull_request:
    branches: [ "docker" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Initialize
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: 'Build and push image'
      run: |
        docker buildx create --use
        docker buildx build --push -t ${{ secrets.ACR_ENDPOINT }}/epg:${{ github.sha }} .
        docker buildx build --push -t ${{ secrets.ACR_ENDPOINT }}/epg:latest .
